version: '3'

services:
  db:
    build: ./mysql
    command: --innodb-use-native-aio=0
    container_name: db
    image: brito/app-db-mysql:latest
    restart: always
    tty: true
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - challenge-network
  
  app:
    container_name: app
    image: brito/node-app:latest
    build: 
      context: nodejs
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    networks:
    - challenge-network  
    tty: true
    depends_on:
      - db

  reverse_proxy:
      build: 
        context: ./nginx
      container_name: nginx
      image: brito/reverse-proxy-nginx:latest
      tty: true
      depends_on:
      - app
      ports:
        - 8080:80
      networks:
        - challenge-network

networks:
  challenge-network:
    driver: bridge